/**
 * 20 Niche Templates for Sun.store
 * 
 * Each template is a complete storefront configuration with unique:
 * - Branding (store name, tagline, logo)
 * - Color palette
 * - Typography
 * - Categories and products
 * - Hero copy
 * 
 * Niches cover: fashion, jewelry, tech, home, beauty, sports, books,
 * toys, pets, art, music, food, wellness, automotive, outdoor, kids,
 * office, vintage, sustainable, luxury.
 */

import type { Template } from "./types";

const baseTypography = {
  bodyFont: "'Manrope', system-ui, sans-serif",
  bodyWeight: 400,
  baseSize: "16px",
  scaleRatio: 1.25,
};

const baseSpacing = {
  shellMaxWidth: "1280px",
  sectionPadding: "6rem",
  cardRadius: "12px",
  buttonRadius: "8px",
};

export const TEMPLATES: Template[] = [
  // ========== 1. JEWELRY ==========
  {
    id: "jewelry",
    name: "Ювелирная мастерская",
    niche: "Ювелирные изделия",
    description: "Элегантные украшения ручной работы",
    colors: {
      background: "#FBF8F3",
      surface: "#FFFFFF",
      surfaceAlt: "#F5EFE6",
      text: "#1A1A1A",
      textMuted: "#6B5D4F",
      accent: "#8B6F47",
      accentText: "#FFFFFF",
      border: "#E8DFD0",
      success: "#4A7C59",
      warning: "#C9A961",
      danger: "#8B3A3A",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Cormorant Garamond', serif",
      displayWeight: 500,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "Золото.Серебро",
      tagline: "Украшения с историей",
      description: "Авторские ювелирные изделия из драгоценных металлов",
      logoMark: "◆",
      iconColor: "#8B6F47",
    },
    categories: [
      {id: "1", name: "Кольца", description: "Обручальные и помолвочные" },
      {id: "2", name: "Серьги", description: "Классические и авторские" },
      {id: "3", name: "Колье", description: "Подвески и цепочки" },
    ],
    products: [
      {
       id: "101",
        slug: "zolotoe-kolco-solnechnoe",
        title: "Кольцо «Солнечное»",
        description: "Золотое кольцо с янтарём, ручная работа",
        price_kopecks: 4500000,
        sku: "JEW-001",
        stock_quantity: 3,
        images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "102",
        slug: "serebryanye-sergi-lunnoy-nochi",
        title: "Серьги «Лунная ночь»",
        description: "Серебряные серьги с лунным камнем",
        price_kopecks: 2800000,
        sku: "JEW-002",
        stock_quantity: 7,
        images: ["https://images.unsplash.com/photo-1535632066274-86a2c9b2e2b7?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "103",
        slug: "kolle-tsarskoe",
        title: "Колье «Царское»",
        description: "Жемчужное ожерелье с золотой застёжкой",
        price_kopecks: 12000000,
        sku: "JEW-003",
        stock_quantity: 2,
        images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "104",
        slug: "pomolvochnoe-kolco-vechnost",
        title: "Кольцо «Вечность»",
        description: "Помолвочное кольцо с бриллиантом 0.5 карата",
        price_kopecks: 35000000,
        sku: "JEW-004",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Авторская коллекция 2025",
      headline: "Украшения, которые становятся семейной реликвией",
      subhead: "Каждое изделие создаётся вручную мастерами с 20-летним опытом",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Заказать консультацию",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 2. FASHION ==========
  {
    id: "fashion",
    name: "Модный бутик",
    niche: "Одежда и мода",
    description: "Современная одежда российских дизайнеров",
    colors: {
      background: "#FFFFFF",
      surface: "#FAFAFA",
      surfaceAlt: "#F0EDE8",
      text: "#0A0A0A",
      textMuted: "#6B6B6B",
      accent: "#FF3B30",
      accentText: "#FFFFFF",
      border: "#E5E5E5",
      success: "#34C759",
      warning: "#FF9500",
      danger: "#FF3B30",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Inter', sans-serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "АТЕЛЬЕ №7",
      tagline: "Современная российская мода",
      description: "Одежда от молодых российских дизайнеров",
      logoMark: "A7",
      iconColor: "#FF3B30",
    },
    categories: [
      {id: "1", name: "Верхняя одежда", description: "Куртки, пальто, жакеты" },
      {id: "2", name: "Базовый гардероб", description: "Футболки, рубашки, брюки" },
      {id: "3", name: "Аксессуары", description: "Сумки, шарфы, украшения" },
    ],
    products: [
      {
       id: "201",
        slug: "palto-moskovskaya-vesna",
        title: "Пальто «Московская весна»",
        description: "Шерстяное пальто прямого кроя",
        price_kopecks: 8900000,
        sku: "FAS-001",
        stock_quantity: 5,
        images: ["https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "202",
        slug: "futbolka-minimalism",
        title: "Футболка «Минимализм»",
        description: "Хлопковая футболка базового кроя",
        price_kopecks: 250000,
        sku: "FAS-002",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "203",
        slug: "sumka-totе",
        title: "Сумка-тоут",
        description: "Кожаная сумка ручной работы",
        price_kopecks: 4500000,
        sku: "FAS-003",
        stock_quantity: 8,
        images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "204",
        slug: "bryuki-cargo-urban",
        title: "Брюки Cargo Urban",
        description: "Брюки карго с накладными карманами",
        price_kopecks: 380000,
        sku: "FAS-004",
        stock_quantity: 12,
        images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800"],
       category_id: "2",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новая коллекция FW25",
      headline: "Одежда, которая говорит за вас",
      subhead: "Российские дизайнеры. Экологичные материалы. Честные цены.",
      ctaPrimary: "Смотреть коллекцию",
      ctaSecondary: "О бренде",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: false,
      showNewsletter: true,
    },
  },

  // ========== 3. TECH ==========
  {
    id: "tech",
    name: "Техно-маркет",
    niche: "Электроника и гаджеты",
    description: "Современная электроника и аксессуары",
    colors: {
      background: "#0A0A0A",
      surface: "#1A1A1A",
      surfaceAlt: "#2A2A2A",
      text: "#FFFFFF",
      textMuted: "#A0A0A0",
      accent: "#00FF88",
      accentText: "#0A0A0A",
      border: "#333333",
      success: "#00FF88",
      warning: "#FFB800",
      danger: "#FF4444",
    },
    typography: {
      ...baseTypography,
      displayFont: "'JetBrains Mono', monospace",
      displayWeight: 600,
      bodyFont: "'Inter', sans-serif",
    },
    spacing: baseSpacing,
    branding: {
      storeName: "TECH.SPACE",
      tagline: "Технологии будущего",
      description: "Электроника, гаджеты, аксессуары",
      logoMark: "◉",
      iconColor: "#00FF88",
    },
    categories: [
      {id: "1", name: "Смартфоны", description: "Флагманы и новинки" },
      {id: "2", name: "Ноутбуки", description: "Для работы и игр" },
      {id: "3", name: "Аксессуары", description: "Наушники, зарядки, чехлы" },
    ],
    products: [
      {
       id: "301",
        slug: "smartphone-future-x",
        title: "Смартфон Future X Pro",
        description: "Флагманский смартфон с ИИ-камерой",
        price_kopecks: 8999000,
        sku: "TECH-001",
        stock_quantity: 15,
        images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "302",
        slug: "laptop-ultra-slim",
        title: "Ноутбук Ultra Slim 15",
        description: "Тонкий и мощный ноутбук для профессионалов",
        price_kopecks: 12999000,
        sku: "TECH-002",
        stock_quantity: 8,
        images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "303",
        slug: "headphones-noise-cancel",
        title: "Наушники с шумоподавлением",
        description: "Беспроводные наушники премиум-класса",
        price_kopecks: 1999000,
        sku: "TECH-003",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "304",
        slug: "smartwatch-active",
        title: "Смарт-часы Active",
        description: "Спортивные часы с GPS и пульсометром",
        price_kopecks: 2499000,
        sku: "TECH-004",
        stock_quantity: 18,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новое поступление",
      headline: "Технологии, которые меняют правила",
      subhead: "Только оригинальная техника с гарантией и быстрой доставкой",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Сравнить модели",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: false,
      showNewsletter: true,
    },
  },

  // ========== 4. HOME & INTERIOR ==========
  {
    id: "home",
    name: "Дом и уют",
    niche: "Декор и интерьер",
    description: "Мебель и предметы интерьера",
    colors: {
      background: "#F5F1EB",
      surface: "#FFFFFF",
      surfaceAlt: "#E8DFD0",
      text: "#2C2416",
      textMuted: "#7A6F5C",
      accent: "#A0826D",
      accentText: "#FFFFFF",
      border: "#D4C9B8",
      success: "#6B8E4E",
      warning: "#C9A961",
      danger: "#A04848",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Playfair Display', serif",
      displayWeight: 600,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "УЮТ.ДОМ",
      tagline: "Создаём пространства для жизни",
      description: "Мебель, декор, текстиль для дома",
      logoMark: "⌂",
      iconColor: "#A0826D",
    },
    categories: [
      {id: "1", name: "Мебель", description: "Диваны, столы, стулья" },
      {id: "2", name: "Декор", description: "Вазы, свечи, зеркала" },
      {id: "3", name: "Текстиль", description: "Пледы, подушки, шторы" },
    ],
    products: [
      {
       id: "401",
        slug: "divan-skandinaviya",
        title: "Диван «Скандинавия»",
        description: "Угловой диван с тканевой обивкой",
        price_kopecks: 45000000,
        sku: "HOME-001",
        stock_quantity: 3,
        images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "402",
        slug: "vaza-keramika",
        title: "Ваза керамическая",
        description: "Ручная работа, высота 35 см",
        price_kopecks: 350000,
        sku: "HOME-002",
        stock_quantity: 12,
        images: ["https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "403",
        slug: "pled-naturalnyy",
        title: "Плед из натуральной шерсти",
        description: "Тёплый плед размером 200×150 см",
        price_kopecks: 590000,
        sku: "HOME-003",
        stock_quantity: 15,
        images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "404",
        slug: "stol-derevyannyy",
        title: "Обеденный стол",
        description: "Массив дуба, 180×90 см",
        price_kopecks: 28000000,
        sku: "HOME-004",
        stock_quantity: 4,
        images: ["https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Коллекция «Скандинавия»",
      headline: "Дом, в который хочется возвращаться",
      subhead: "Натуральные материалы, лаконичные формы, продуманный дизайн",
      ctaPrimary: "Смотреть коллекцию",
      ctaSecondary: "Дизайн-консультация",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 5. BEAUTY ==========
  {
    id: "beauty",
    name: "Красота и уход",
    niche: "Косметика и уход",
    description: "Премиальная косметика и парфюмерия",
    colors: {
      background: "#FFF5F7",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4E9",
      text: "#1A1A1A",
      textMuted: "#8B6B6F",
      accent: "#E91E63",
      accentText: "#FFFFFF",
      border: "#F5D5DC",
      success: "#4CAF50",
      warning: "#FF9800",
      danger: "#F44336",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Cormorant Garamond', serif",
      displayWeight: 400,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "BEAUTÉ",
      tagline: "Красота без компромиссов",
      description: "Премиальная косметика мировых брендов",
      logoMark: "❀",
      iconColor: "#E91E63",
    },
    categories: [
      {id: "1", name: "Уход за лицом", description: "Кремы, сыворотки, маски" },
      {id: "2", name: "Макияж", description: "Помады, тени, тональные" },
      {id: "3", name: "Парфюмерия", description: "Духи и ароматы" },
    ],
    products: [
      {
       id: "501",
        slug: "syvorotka-vitamin-c",
        title: "Сыворотка с витамином С",
        description: "Осветляющая сыворотка для сияния кожи",
        price_kopecks: 290000,
        sku: "BEAU-001",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "502",
        slug: "pomada-velvet-rose",
        title: "Помада Velvet Rose",
        description: "Матовая помада стойкостью 12 часов",
        price_kopecks: 89000,
        sku: "BEAU-002",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "503",
        slug: "duhi-rose-noir",
        title: "Духи «Rose Noir»",
        description: "Парфюмерная вода 50 мл",
        price_kopecks: 850000,
        sku: "BEAU-003",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "504",
        slug: "krem-anti-age",
        title: "Крем Anti-Age",
        description: "Омолаживающий крем для лица",
        price_kopecks: 450000,
        sku: "BEAU-004",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новая коллекция ухода",
      headline: "Красота, которая раскрывает вашу индивидуальность",
      subhead: "Только оригинальная косметика с сертификатами качества",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Пробники",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 6. SPORTS ==========
  {
    id: "sports",
    name: "Спорт и фитнес",
    niche: "Спортивные товары",
    description: "Спортивное оборудование и одежда",
    colors: {
      background: "#FFFFFF",
      surface: "#F5F5F5",
      surfaceAlt: "#E8E8E8",
      text: "#0A0A0A",
      textMuted: "#5A5A5A",
      accent: "#FF6B35",
      accentText: "#FFFFFF",
      border: "#D0D0D0",
      success: "#00C853",
      warning: "#FFB300",
      danger: "#D32F2F",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Oswald', sans-serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "POWER.SPORT",
      tagline: "Твой путь к рекордам",
      description: "Спортивное оборудование и экипировка",
      logoMark: "⚡",
      iconColor: "#FF6B35",
    },
    categories: [
      {id: "1", name: "Тренажёры", description: "Домашнее оборудование" },
      {id: "2", name: "Одежда", description: "Спортивная форма" },
      {id: "3", name: "Аксессуары", description: "Гантели, скакалки, коврики" },
    ],
    products: [
      {
       id: "601",
        slug: "trenazher-begovaya-dorozhka",
        title: "Беговая дорожка Pro",
        description: "Профессиональная беговая дорожка для дома",
        price_kopecks: 89000000,
        sku: "SPORT-001",
        stock_quantity: 5,
        images: ["https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "602",
        slug: "krossovki-running-pro",
        title: "Кроссовки Running Pro",
        description: "Беговые кроссовки с амортизацией",
        price_kopecks: 590000,
        sku: "SPORT-002",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "603",
        slug: "ganteli-nabor",
        title: "Набор гантелей 20 кг",
        description: "Регулируемые гантели 2×10 кг",
        price_kopecks: 350000,
        sku: "SPORT-003",
        stock_quantity: 15,
        images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "604",
        slug: "kovrik-dlya-yogi",
        title: "Коврик для йоги",
        description: "Нескользящий коврик 6 мм",
        price_kopecks: 89000,
        sku: "SPORT-004",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Сезонные скидки до 40%",
      headline: "Стань лучшей версией себя",
      subhead: "Профессиональное оборудование для дома и зала",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Программы тренировок",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 7. BOOKS ==========
  {
    id: "books",
    name: "Книжный магазин",
    niche: "Книги и литература",
    description: "Книги, журналы, учебники",
    colors: {
      background: "#FAF6F0",
      surface: "#FFFFFF",
      surfaceAlt: "#F0E8D8",
      text: "#1A1A1A",
      textMuted: "#6B5D4F",
      accent: "#8B4513",
      accentText: "#FFFFFF",
      border: "#D4C5A8",
      success: "#4A7C59",
      warning: "#C9A961",
      danger: "#8B3A3A",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Merriweather', serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "КНИЖНЫЙ.ДВОР",
      tagline: "Мир знаний на вашей полке",
      description: "Книги, учебники, журналы",
      logoMark: "📖",
      iconColor: "#8B4513",
    },
    categories: [
      {id: "1", name: "Художественная литература", description: "Романы, поэзия, проза" },
      {id: "2", name: "Учебники", description: "Школьные и вузовские" },
      {id: "3", name: "Детские книги", description: "Сказки, развивающие" },
    ],
    products: [
      {
       id: "701",
        slug: "voina-i-mir-tom-1",
        title: "Война и мир. Том 1",
        description: "Л. Н. Толстой. Полное издание",
        price_kopecks: 89000,
        sku: "BOOK-001",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "702",
        slug: "uchebnik-matematiki-9-klass",
        title: "Математика 9 класс",
        description: "Учебник для общеобразовательных школ",
        price_kopecks: 65000,
        sku: "BOOK-002",
        stock_quantity: 100,
        images: ["https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "703",
        slug: "skazki-dlya-detey",
        title: "Сказки для детей",
        description: "Сборник лучших русских сказок",
        price_kopecks: 45000,
        sku: "BOOK-003",
        stock_quantity: 80,
        images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "704",
        slug: "master-i-margarita",
        title: "Мастер и Маргарита",
        description: "М. А. Булгаков. Юбилейное издание",
        price_kopecks: 75000,
        sku: "BOOK-004",
        stock_quantity: 60,
        images: ["https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Книжные новинки сезона",
      headline: "Книга — лучший подарок",
      subhead: "Бесплатная доставка от 2000 ₽ по всей России",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Бестселлеры",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 8. TOYS ==========
  {
    id: "toys",
    name: "Детские игрушки",
    niche: "Игрушки и игры",
    description: "Развивающие игрушки и настольные игры",
    colors: {
      background: "#FFF8E7",
      surface: "#FFFFFF",
      surfaceAlt: "#FFEFB8",
      text: "#1A1A1A",
      textMuted: "#6B5D4F",
      accent: "#FF6B6B",
      accentText: "#FFFFFF",
      border: "#F0D88C",
      success: "#4ECDC4",
      warning: "#FFE66D",
      danger: "#FF6B6B",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Fredoka', sans-serif",
      displayWeight: 600,
      bodyFont: "'Nunito', sans-serif",
    },
    spacing: baseSpacing,
    branding: {
      storeName: "ИГРУШКИН",
      tagline: "Мир весёлых игр",
      description: "Игрушки, настольные игры, творчество",
      logoMark: "🧸",
      iconColor: "#FF6B6B",
    },
    categories: [
      {id: "1", name: "Развивающие игрушки", description: "Для малышей и дошкольников" },
      {id: "2", name: "Настольные игры", description: "Для всей семьи" },
      {id: "3", name: "Творчество", description: "Рисование, лепка, рукоделие" },
    ],
    products: [
      {
       id: "801",
        slug: "konstruktor-lego-city",
        title: "Конструктор «Город»",
        description: "Конструктор с 500 деталями",
        price_kopecks: 350000,
        sku: "TOY-001",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1558060370-d4d8b1db0d52?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "802",
        slug: "nastolnaya-igra-monopoly",
        title: "Монополия",
        description: "Классическая настольная игра",
        price_kopecks: 250000,
        sku: "TOY-002",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "803",
        slug: "plastilin-24-cveta",
        title: "Пластилин 24 цвета",
        description: "Набор для творчества",
        price_kopecks: 35000,
        sku: "TOY-003",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "804",
        slug: "myagkaya-igrushka-zayka",
        title: "Мягкая игрушка «Зайка»",
        description: "Плюшевая игрушка 30 см",
        price_kopecks: 89000,
        sku: "TOY-004",
        stock_quantity: 40,
        images: ["https://images.unsplash.com/photo-1559454403-b8fb88521f99?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Игрушки со скидкой 20%",
      headline: "Счастье в каждой игрушке",
      subhead: "Безопасные материалы, развивающие функции",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "По возрасту",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 9. PETS ==========
  {
    id: "pets",
    name: "Зоомагазин",
    niche: "Товары для животных",
    description: "Корма, аксессуары, игрушки для питомцев",
    colors: {
      background: "#F0F8E8",
      surface: "#FFFFFF",
      surfaceAlt: "#E0F0D0",
      text: "#1A1A1A",
      textMuted: "#5A6B4F",
      accent: "#7CB342",
      accentText: "#FFFFFF",
      border: "#C5DBA8",
      success: "#7CB342",
      warning: "#FFA726",
      danger: "#E57373",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Quicksand', sans-serif",
      displayWeight: 600,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "ЛАПКА.МАРКЕТ",
      tagline: "Всё для ваших любимцев",
      description: "Корма, аксессуары, ветеринария",
      logoMark: "🐾",
      iconColor: "#7CB342",
    },
    categories: [
      {id: "1", name: "Корма", description: "Сухие и влажные" },
      {id: "2", name: "Аксессуары", description: "Поводки, лежанки, игрушки" },
      {id: "3", name: "Груминг", description: "Шампуни, расчёски" },
    ],
    products: [
      {
       id: "901",
        slug: "korm-dlya-sobak-premium",
        title: "Корм премиум для собак",
        description: "Сухой корм 15 кг, говядина",
        price_kopecks: 450000,
        sku: "PET-001",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1589941013453-ec8982c96e45?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "902",
        slug: "povodok-dlya-sobaki",
        title: "Поводок для собаки",
        description: "Кожаный, длина 1.5 м",
        price_kopecks: 89000,
        sku: "PET-002",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "903",
        slug: "lezhanka-dlya-kota",
        title: "Лежанка для кота",
        description: "Мягкая лежанка с бортиками",
        price_kopecks: 150000,
        sku: "PET-003",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "904",
        slug: "shampun-dlya-sobak",
        title: "Шампунь для собак",
        description: "Гипоаллергенный, 500 мл",
        price_kopecks: 45000,
        sku: "PET-004",
        stock_quantity: 40,
        images: ["https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новинки для ваших питомцев",
      headline: "Забота, которая видна",
      subhead: "Качественные товары для здоровья и счастья питомцев",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Советы ветеринара",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 10. ART ==========
  {
    id: "art",
    name: "Галерея искусств",
    niche: "Искусство и антиквариат",
    description: "Картины, скульптуры, антиквариат",
    colors: {
      background: "#FAFAFA",
      surface: "#FFFFFF",
      surfaceAlt: "#F0F0F0",
      text: "#1A1A1A",
      textMuted: "#6B6B6B",
      accent: "#9C27B0",
      accentText: "#FFFFFF",
      border: "#E0E0E0",
      success: "#4CAF50",
      warning: "#FF9800",
      danger: "#F44336",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Cormorant Garamond', serif",
      displayWeight: 500,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "АРТ.ГАЛЕРЕЯ",
      tagline: "Искусство в вашем пространстве",
      description: "Авторские работы и репродукции",
      logoMark: "🎨",
      iconColor: "#9C27B0",
    },
    categories: [
      {id: "1", name: "Живопись", description: "Картины маслом и акрилом" },
      {id: "2", name: "Скульптура", description: "Декоративные фигуры" },
      {id: "3", name: "Антиквариат", description: "Винтажные предметы" },
    ],
    products: [
      {
       id: "1001",
        slug: "kartina-moskovskiy-peyzazh",
        title: "«Московский пейзаж»",
        description: "Холст, масло, 80×60 см",
        price_kopecks: 45000000,
        sku: "ART-001",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1002",
        slug: "skulptura-angel",
        title: "Скульптура «Ангел»",
        description: "Бронза, высота 40 см",
        price_kopecks: 28000000,
        sku: "ART-002",
        stock_quantity: 2,
        images: ["https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1003",
        slug: "vintazhnye-chasy",
        title: "Винтажные часы",
        description: "СССР, 1960-е годы",
        price_kopecks: 12000000,
        sku: "ART-003",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1004",
        slug: "reprodukciya-zvezdnaya-noch",
        title: "«Звёздная ночь»",
        description: "Репродукция Ван Гога, багет",
        price_kopecks: 890000,
        sku: "ART-004",
        stock_quantity: 8,
        images: ["https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Выставка современного искусства",
      headline: "Искусство, которое вдохновляет",
      subhead: "Авторские работы российских и зарубежных художников",
      ctaPrimary: "Смотреть коллекцию",
      ctaSecondary: "О галерее",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 11. MUSIC ==========
  {
    id: "music",
    name: "Музыкальный магазин",
    niche: "Музыкальные инструменты",
    description: "Инструменты, оборудование, аксессуары",
    colors: {
      background: "#0A0A0A",
      surface: "#1A1A1A",
      surfaceAlt: "#2A2A2A",
      text: "#FFFFFF",
      textMuted: "#A0A0A0",
      accent: "#FF4081",
      accentText: "#FFFFFF",
      border: "#333333",
      success: "#00E676",
      warning: "#FFC107",
      danger: "#FF5252",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Bebas Neue', sans-serif",
      displayWeight: 700,
      bodyFont: "'Inter', sans-serif",
    },
    spacing: baseSpacing,
    branding: {
      storeName: "MUSIC.STORE",
      tagline: "Твой звук, твоя музыка",
      description: "Инструменты и оборудование для музыкантов",
      logoMark: "♪",
      iconColor: "#FF4081",
    },
    categories: [
      {id: "1", name: "Гитары", description: "Акустические и электро" },
      {id: "2", name: "Клавишные", description: "Пианино, синтезаторы" },
      {id: "3", name: "Аксессуары", description: "Струны, медиаторы, чехлы" },
    ],
    products: [
      {
       id: "1101",
        slug: "gitara-fender-stratocaster",
        title: "Fender Stratocaster",
        description: "Электрогитара, легендарная модель",
        price_kopecks: 85000000,
        sku: "MUS-001",
        stock_quantity: 3,
        images: ["https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1102",
        slug: "sintezator-yamaha",
        title: "Синтезатор Yamaha PSR",
        description: "61 клавиша, 800 тембров",
        price_kopecks: 45000000,
        sku: "MUS-002",
        stock_quantity: 5,
        images: ["https://images.unsplash.com/photo-1552422535-c45813c61732?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1103",
        slug: "struny-dlya-gitary",
        title: "Струны для гитары",
        description: "Комплект, калибр .010-.046",
        price_kopecks: 89000,
        sku: "MUS-003",
        stock_quantity: 100,
        images: ["https://images.unsplash.com/photo-1605020420620-20c943cc4669?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1104",
        slug: "akusticheskaya-gitara",
        title: "Акустическая гитара",
        description: "Ёль, верхняя дека, натуральный цвет",
        price_kopecks: 25000000,
        sku: "MUS-004",
        stock_quantity: 8,
        images: ["https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новая коллекция 2025",
      headline: "Музыка начинается здесь",
      subhead: "Профессиональные инструменты для начинающих и профи",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Аренда инструментов",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 12. FOOD & GOURMET ==========
  {
    id: "food",
    name: "Гастрономия",
    niche: "Продукты и деликатесы",
    description: "Деликатесы, чай, кофе, сладости",
    colors: {
      background: "#FFF8F0",
      surface: "#FFFFFF",
      surfaceAlt: "#F5E6D3",
      text: "#2C1810",
      textMuted: "#7A5C4F",
      accent: "#D2691E",
      accentText: "#FFFFFF",
      border: "#E8D4B8",
      success: "#8B6F47",
      warning: "#C9A961",
      danger: "#8B3A3A",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Playfair Display', serif",
      displayWeight: 600,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "ГАСТРО.МАРКЕТ",
      tagline: "Вкус настоящей еды",
      description: "Деликатесы и фермерские продукты",
      logoMark: "🍷",
      iconColor: "#D2691E",
    },
    categories: [
      {id: "1", name: "Чай и кофе", description: "Элитные сорта" },
      {id: "2", name: "Сыры и колбасы", description: "Фермерские деликатесы" },
      {id: "3", name: "Сладости", description: "Шоколад, десерты" },
    ],
    products: [
      {
       id: "1201",
        slug: "kofe-arabika-1kg",
        title: "Кофе Арабика 1 кг",
        description: "Свежеобжаренный, Эфиопия",
        price_kopecks: 250000,
        sku: "FOOD-001",
        stock_quantity: 40,
        images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1202",
        slug: "syr-parmezan",
        title: "Сыр Пармезан",
        description: "Выдержка 24 месяца, 500 г",
        price_kopecks: 450000,
        sku: "FOOD-002",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1203",
        slug: "shokolad-belgiyskiy",
        title: "Бельгийский шоколад",
        description: "Ручной работы, 70% какао",
        price_kopecks: 89000,
        sku: "FOOD-003",
        stock_quantity: 60,
        images: ["https://images.unsplash.com/photo-1511381939415-e44015466834?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1204",
        slug: "chay-darjeeling",
        title: "Чай Дарджилинг",
        description: "Элитный сорт, 100 г",
        price_kopecks: 65000,
        sku: "FOOD-004",
        stock_quantity: 35,
        images: ["https://images.unsplash.com/photo-1597318236896-4d2eb8c5b1d1?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Фермерские продукты",
      headline: "Вкус, который помнят",
      subhead: "Натуральные продукты от лучших производителей",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Подарочные наборы",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 13. WELLNESS ==========
  {
    id: "wellness",
    name: "Здоровье и wellness",
    niche: "Здоровье и красота",
    description: "Витамины, БАДы, натуральная косметика",
    colors: {
      background: "#F0F7F0",
      surface: "#FFFFFF",
      surfaceAlt: "#E0F0E0",
      text: "#1A2E1A",
      textMuted: "#5A6B5A",
      accent: "#4CAF50",
      accentText: "#FFFFFF",
      border: "#C5DBC5",
      success: "#4CAF50",
      warning: "#FFA726",
      danger: "#E57373",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Lora', serif",
      displayWeight: 500,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "WELLNESS.HUB",
      tagline: "Здоровье — это путь",
      description: "Витамины, натуральная косметика, эко-товары",
      logoMark: "🌿",
      iconColor: "#4CAF50",
    },
    categories: [
      {id: "1", name: "Витамины и БАДы", description: "Для здоровья и иммунитета" },
      {id: "2", name: "Натуральная косметика", description: "Органические средства" },
      {id: "3", name: "Ароматерапия", description: "Эфирные масла, свечи" },
    ],
    products: [
      {
       id: "1301",
        slug: "vitaminy-d3-2000",
        title: "Витамин D3 2000 МЕ",
        description: "60 капсул, для иммунитета",
        price_kopecks: 89000,
        sku: "WELL-001",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1550572017-edd951b55104?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1302",
        slug: "efirnoe-maslo-lavanda",
        title: "Эфирное масло лаванды",
        description: "Натуральное, 15 мл",
        price_kopecks: 65000,
        sku: "WELL-002",
        stock_quantity: 40,
        images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1303",
        slug: "organic-krem-dlya-litsa",
        title: "Органический крем для лица",
        description: "С алоэ вера, 50 мл",
        price_kopecks: 150000,
        sku: "WELL-003",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1304",
        slug: "magniy-b6",
        title: "Магний B6",
        description: "Для нервной системы, 30 таблеток",
        price_kopecks: 75000,
        sku: "WELL-004",
        stock_quantity: 45,
        images: ["https://images.unsplash.com/photo-1550572017-edd951b55104?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Эко-продукты для здоровья",
      headline: "Забота о себе каждый день",
      subhead: "Натуральные ингредиенты, проверенное качество",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Консультация нутрициолога",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 14. AUTOMOTIVE ==========
  {
    id: "auto",
    name: "Автотовары",
    niche: "Автомобильные товары",
    description: "Запчасти, аксессуары, инструменты",
    colors: {
      background: "#1A1A1A",
      surface: "#2A2A2A",
      surfaceAlt: "#3A3A3A",
      text: "#FFFFFF",
      textMuted: "#B0B0B0",
      accent: "#FF6B00",
      accentText: "#FFFFFF",
      border: "#444444",
      success: "#00C853",
      warning: "#FFB300",
      danger: "#FF1744",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Roboto Condensed', sans-serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "AUTO.PARTS",
      tagline: "Качественные запчасти для вашего авто",
      description: "Оригинальные и аналоговые запчасти",
      logoMark: "🚗",
      iconColor: "#FF6B00",
    },
    categories: [
      {id: "1", name: "Запчасти", description: "Двигатель, подвеска, тормоза" },
      {id: "2", name: "Аксессуары", description: "Чехлы, коврики, держатели" },
      {id: "3", name: "Масла и жидкости", description: "Моторные, трансмиссионные" },
    ],
    products: [
      {
       id: "1401",
        slug: "maslo-motornoe-5w30",
        title: "Моторное масло 5W-30",
        description: "Синтетика, 4 литра",
        price_kopecks: 350000,
        sku: "AUTO-001",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1402",
        slug: "tormoznye-kolodki",
        title: "Тормозные колодки",
        description: "Передние, для Toyota Camry",
        price_kopecks: 250000,
        sku: "AUTO-002",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1403",
        slug: "avto-kovriki",
        title: "Автомобильные коврики",
        description: "Резиновые, комплект 4 шт",
        price_kopecks: 180000,
        sku: "AUTO-003",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1404",
        slug: "avtomobilnyy-pylesos",
        title: "Автомобильный пылесос",
        description: "Беспроводной, мощный",
        price_kopecks: 450000,
        sku: "AUTO-004",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"],
       category_id: "2",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Запчасти со скидкой",
      headline: "Всё для вашего автомобиля",
      subhead: "Оригинальные запчасти с гарантией и быстрой доставкой",
      ctaPrimary: "Подобрать запчасти",
      ctaSecondary: "По марке авто",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 15. OUTDOOR ==========
  {
    id: "outdoor",
    name: "Активный отдых",
    niche: "Туризм и outdoor",
    description: "Снаряжение для туризма и активного отдыха",
    colors: {
      background: "#F5F5DC",
      surface: "#FFFFFF",
      surfaceAlt: "#E8E8C8",
      text: "#2C4A2C",
      textMuted: "#5A6B5A",
      accent: "#228B22",
      accentText: "#FFFFFF",
      border: "#C5DBA8",
      success: "#228B22",
      warning: "#FFA500",
      danger: "#DC143C",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Bebas Neue', sans-serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "OUTDOOR.EXP",
      tagline: "Твои приключения начинаются",
      description: "Снаряжение для туризма и активного отдыха",
      logoMark: "⛰",
      iconColor: "#228B22",
    },
    categories: [
      {id: "1", name: "Палатки и тенты", description: "Для кемпинга и походов" },
      {id: "2", name: "Рюкзаки", description: "Туристические и городские" },
      {id: "3", name: "Спальные мешки", description: "Для разных температур" },
    ],
    products: [
      {
       id: "1501",
        slug: "palatka-3-mesta",
        title: "Палатка 3-местная",
        description: "Водонепроницаемая, 3 сезона",
        price_kopecks: 890000,
        sku: "OUT-001",
        stock_quantity: 15,
        images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1502",
        slug: "ryukzak-turisticheskiy",
        title: "Рюкзак туристический 60л",
        description: "С системой вентиляции спины",
        price_kopecks: 650000,
        sku: "OUT-002",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1622260614153-03223fb72052?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1503",
        slug: "spalnyy-meshok",
        title: "Спальный мешок",
        description: "Температура комфорта -5°C",
        price_kopecks: 450000,
        sku: "OUT-003",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1571863533956-01c88e79957e?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1504",
        slug: "gorełka-turisticheskaya",
        title: "Туристическая горелка",
        description: "Газовая, компактная",
        price_kopecks: 350000,
        sku: "OUT-004",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Сезон активного отдыха",
      headline: "Готов к любым приключениям",
      subhead: "Профессиональное снаряжение для туризма",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Гид по снаряжению",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 16. KIDS ==========
  {
    id: "kids",
    name: "Детский мир",
    niche: "Детские товары",
    description: "Одежда, обувь, аксессуары для детей",
    colors: {
      background: "#FFF0F5",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4E1",
      text: "#1A1A1A",
      textMuted: "#6B5D6B",
      accent: "#FF69B4",
      accentText: "#FFFFFF",
      border: "#F5D5DC",
      success: "#4CAF50",
      warning: "#FFC107",
      danger: "#F44336",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Fredoka', sans-serif",
      displayWeight: 600,
      bodyFont: "'Nunito', sans-serif",
    },
    spacing: baseSpacing,
    branding: {
      storeName: "МАЛЫШАМ.РУ",
      tagline: "Всё лучшее для ваших малышей",
      description: "Детская одежда, обувь, игрушки",
      logoMark: "👶",
      iconColor: "#FF69B4",
    },
    categories: [
      {id: "1", name: "Одежда", description: "Для мальчиков и девочек" },
      {id: "2", name: "Обувь", description: "Удобная и безопасная" },
      {id: "3", name: "Аксессуары", description: "Рюкзаки, шапки, варежки" },
    ],
    products: [
      {
       id: "1601",
        slug: "kombinezon-detskiy",
        title: "Детский комбинезон",
        description: "Тёплый, для зимы, размер 86",
        price_kopecks: 350000,
        sku: "KID-001",
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1602",
        slug: "krossovki-detskie",
        title: "Детские кроссовки",
        description: "Светящиеся, размер 32",
        price_kopecks: 150000,
        sku: "KID-002",
        stock_quantity: 25,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1603",
        slug: "ryukzak-shkolnyy",
        title: "Школьный рюкзак",
        description: "С ортопедической спинкой",
        price_kopecks: 250000,
        sku: "KID-003",
        stock_quantity: 20,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "1604",
        slug: "futbolka-detskaya",
        title: "Детская футболка",
        description: "Хлопок 100%, яркий принт",
        price_kopecks: 65000,
        sku: "KID-004",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800"],
       category_id: "1",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Новая коллекция детской одежды",
      headline: "Малышам — только лучшее",
      subhead: "Натуральные материалы, яркие дизайны, доступные цены",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "По возрасту",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 17. OFFICE ==========
  {
    id: "office",
    name: "Офис и канцелярия",
    niche: "Офисные товары",
    description: "Канцелярия, мебель, техника для офиса",
    colors: {
      background: "#FFFFFF",
      surface: "#FAFAFA",
      surfaceAlt: "#F0F0F0",
      text: "#0A0A0A",
      textMuted: "#5A5A5A",
      accent: "#2196F3",
      accentText: "#FFFFFF",
      border: "#E0E0E0",
      success: "#4CAF50",
      warning: "#FF9800",
      danger: "#F44336",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Inter', sans-serif",
      displayWeight: 600,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "OFFICE.PRO",
      tagline: "Всё для продуктивной работы",
      description: "Канцелярия, мебель, техника",
      logoMark: "📋",
      iconColor: "#2196F3",
    },
    categories: [
      {id: "1", name: "Канцелярия", description: "Ручки, тетради, папки" },
      {id: "2", name: "Офисная мебель", description: "Столы, кресла, шкафы" },
      {id: "3", name: "Техника", description: "Принтеры, сканеры, ИБП" },
    ],
    products: [
      {
       id: "1701",
        slug: "kreslo-rukovoditelya",
        title: "Кресло руководителя",
        description: "Эргономичное, с поясничной поддержкой",
        price_kopecks: 15000000,
        sku: "OFF-001",
        stock_quantity: 8,
        images: ["https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1702",
        slug: "stol-ofisnyy",
        title: "Офисный стол",
        description: "С тумбой, 160×80 см",
        price_kopecks: 12000000,
        sku: "OFF-002",
        stock_quantity: 10,
        images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1703",
        slug: "nabor-ruchek",
        title: "Набор ручек",
        description: "Шариковые, 10 цветов",
        price_kopecks: 45000,
        sku: "OFF-003",
        stock_quantity: 100,
        images: ["https://images.unsplash.com/photo-1583485088034-697b5bc36b92?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1704",
        slug: "printer-laser",
        title: "Лазерный принтер",
        description: "Чёрно-белый, A4",
        price_kopecks: 8900000,
        sku: "OFF-004",
        stock_quantity: 12,
        images: ["https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Офисные решения для бизнеса",
      headline: "Создаём пространство для работы",
      subhead: "Качественная мебель и техника для вашего офиса",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Корпоративные заказы",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 18. VINTAGE ==========
  {
    id: "vintage",
    name: "Винтаж и ретро",
    niche: "Винтажные вещи",
    description: "Винтажная одежда, мебель, аксессуары",
    colors: {
      background: "#F5E8D0",
      surface: "#FFFFFF",
      surfaceAlt: "#E8D4B0",
      text: "#3A2418",
      textMuted: "#7A5C4F",
      accent: "#8B6F47",
      accentText: "#FFFFFF",
      border: "#D4B890",
      success: "#6B8E4E",
      warning: "#C9A961",
      danger: "#8B3A3A",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Playfair Display', serif",
      displayWeight: 700,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "VINTAGE.ATELIER",
      tagline: "История в каждой вещи",
      description: "Винтажная одежда и аксессуары",
      logoMark: "⌘",
      iconColor: "#8B6F47",
    },
    categories: [
      {id: "1", name: "Винтажная одежда", description: "1950-1980-е годы" },
      {id: "2", name: "Аксессуары", description: "Сумки, украшения, шляпы" },
      {id: "3", name: "Мебель", description: "СССР и Европа" },
    ],
    products: [
      {
       id: "1801",
        slug: "vintazhnoe-plate-60h",
        title: "Винтажное платье 1960-х",
        description: "Шерсть, оригинал, размер S",
        price_kopecks: 3500000,
        sku: "VIN-001",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1802",
        slug: "vintazhnaya-sumka",
        title: "Винтажная сумка",
        description: "Кожа, 1970-е, Италия",
        price_kopecks: 4500000,
        sku: "VIN-002",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1803",
        slug: "vintazhnyy-shlyapa",
        title: "Винтажная шляпа",
        description: "Фетр, 1950-е годы",
        price_kopecks: 1500000,
        sku: "VIN-003",
        stock_quantity: 2,
        images: ["https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1804",
        slug: "vintazhnoe-kreslo",
        title: "Винтажное кресло",
        description: "Бархат, 1960-е, реставрация",
        price_kopecks: 25000000,
        sku: "VIN-004",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Коллекция винтажа",
      headline: "Вещи с характером и историей",
      subhead: "Тщательно отобранные предметы из прошлого",
      ctaPrimary: "Смотреть коллекцию",
      ctaSecondary: "Об истории вещей",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 19. SUSTAINABLE ==========
  {
    id: "sustainable",
    name: "Эко и sustainable",
    niche: "Экологичные товары",
    description: "Экологичная и sustainable продукция",
    colors: {
      background: "#F0F5E8",
      surface: "#FFFFFF",
      surfaceAlt: "#E0F0D0",
      text: "#1A2E1A",
      textMuted: "#5A6B5A",
      accent: "#2E7D32",
      accentText: "#FFFFFF",
      border: "#C5DBA8",
      success: "#2E7D32",
      warning: "#FFA726",
      danger: "#E57373",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Lora', serif",
      displayWeight: 500,
    },
    spacing: baseSpacing,
    branding: {
      storeName: "ECO.LIVING",
      tagline: "Осознанное потребление",
      description: "Экологичные товары для жизни",
      logoMark: "🌱",
      iconColor: "#2E7D32",
    },
    categories: [
      {id: "1", name: "Эко-косметика", description: "Натуральные ингредиенты" },
      {id: "2", name: "Многоразовое", description: "Сумки, бутылки, контейнеры" },
      {id: "3", name: "Органик-еда", description: "Эко-продукты" },
    ],
    products: [
      {
       id: "1901",
        slug: "ekologicheskaya-sumka",
        title: "Эко-сумка хлопковая",
        description: "Многоразовая, органический хлопок",
        price_kopecks: 89000,
        sku: "ECO-001",
        stock_quantity: 50,
        images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1902",
        slug: "bambukovaya-zubnaya-shchetka",
        title: "Бамбуковая зубная щётка",
        description: "Биоразлагаемая, 4 шт в упаковке",
        price_kopecks: 35000,
        sku: "ECO-002",
        stock_quantity: 100,
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "1903",
        slug: "metallicheskaya-butylka",
        title: "Металлическая бутылка",
        description: "Для воды, 750 мл",
        price_kopecks: 65000,
        sku: "ECO-003",
        stock_quantity: 60,
        images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "1904",
        slug: "organik-maslo-coconut",
        title: "Органическое кокосовое масло",
        description: "Холодного отжима, 500 мл",
        price_kopecks: 150000,
        sku: "ECO-004",
        stock_quantity: 40,
        images: ["https://images.unsplash.com/photo-1597318236896-4d2eb8c5b1d1?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Осознанное потребление",
      headline: "Забота о планете в каждой покупке",
      subhead: "Экологичные товары для тех, кому не всё равно",
      ctaPrimary: "Смотреть каталог",
      ctaSecondary: "Наша миссия",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },

  // ========== 20. LUXURY ==========
  {
    id: "luxury",
    name: "Премиум и люкс",
    niche: "Премиум-товары",
    description: "Эксклюзивные товары премиум-класса",
    colors: {
      background: "#0A0A0A",
      surface: "#1A1A1A",
      surfaceAlt: "#2A2A2A",
      text: "#FFFFFF",
      textMuted: "#A0A0A0",
      accent: "#D4AF37",
      accentText: "#0A0A0A",
      border: "#333333",
      success: "#4CAF50",
      warning: "#FFC107",
      danger: "#F44336",
    },
    typography: {
      ...baseTypography,
      displayFont: "'Cormorant Garamond', serif",
      displayWeight: 500,
    },
    spacing: {
      shellMaxWidth: "1400px",
      sectionPadding: "8rem",
      cardRadius: "4px",
      buttonRadius: "2px",
    },
    branding: {
      storeName: "MAISON DE LUXE",
      tagline: "Исключительное для исключительных",
      description: "Эксклюзивные товары премиум-класса",
      logoMark: "✦",
      iconColor: "#D4AF37",
    },
    categories: [
      {id: "1", name: "Ювелирные изделия", description: "Эксклюзивные украшения" },
      {id: "2", name: "Часы", description: "Швейцарские механические" },
      {id: "3", name: "Аксессуары", description: "Кожа, кашемир, шёлк" },
    ],
    products: [
      {
       id: "2001",
        slug: "chasy-rolex-submariner",
        title: "Rolex Submariner",
        description: "Швейцарские часы, оригинал",
        price_kopecks: 850000000,
        sku: "LUX-001",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800"],
       category_id: "2",
        is_active: true,
      },
      {
       id: "2002",
        slug: "koltso-cartier",
        title: "Кольцо Cartier",
        description: "Золото, бриллианты, оригинал",
        price_kopecks: 450000000,
        sku: "LUX-002",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800"],
       category_id: "1",
        is_active: true,
      },
      {
       id: "2003",
        slug: "sumka-hermes-birkin",
        title: "Hermès Birkin",
        description: "Кожа, ручная работа, оригинал",
        price_kopecks: 1200000000,
        sku: "LUX-003",
        stock_quantity: 1,
        images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800"],
       category_id: "3",
        is_active: true,
      },
      {
       id: "2004",
        slug: "sharf-cashmere",
        title: "Кашемировый шарф",
        description: "100% кашемир, Италия",
        price_kopecks: 25000000,
        sku: "LUX-004",
        stock_quantity: 5,
        images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800"],
       category_id: "3",
        is_active: true,
      },
    ],
    heroCopy: {
      eyebrow: "Эксклюзивная коллекция",
      headline: "Искусство роскоши",
      subhead: "Уникальные предметы для ценителей совершенства",
      ctaPrimary: "Смотреть коллекцию",
      ctaSecondary: "Персональный консультант",
    },
    sections: {
      showFeatured: true,
      showCollections: true,
      showTestimonials: true,
      showNewsletter: true,
    },
  },
];

// Helper functions
export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getTemplateIds(): string[] {
  return TEMPLATES.map((t) => t.id);
}

export function getDefaultTemplate(): Template {
  return TEMPLATES[0];
}
